# Site settings
title: Securit Weekly Blog
url: "http://lyxw.github.io"    # the protocol and hostname of your site
baseurl: "/"    # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Chongqing
description: >
  The quiter you become, the more you can hear.

# Your information
#email: your_email@example.com
author: lyxw
avatar: "/images/author.jpg"
profile: The quiter you become, the more you can hear.
twitter_username: kylin
github_username:  lyxw

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title/:categories/:month/:day/:year
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
