title: lyxw blog
description: My Personal Blog
author: lyxw
logo: /static/img/avatar.png
github: https://github.com/lyxw
about: Freelance developer

baseurl: "https://lyxw.github.io"
url: "https://lyxw.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \lyxw
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
