# Site settings
title: Security Weekly Blog
url: "https://lyxw.github.io"    # the protocol and hostname of your site
baseurl: "/"    # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Chongqing
description: >
  The quiter you become, the more you can hear.

# Your information
#email: your_email@example.com
author: lyxw
avatar: "/images/author.jpg"
profile: The quiter you become, the more you can hear.
#twitter_username: kylin
github_username: lyxw
gitee_username: allmost
wxgzh_username: /about

include: [_layouts, _includes, _posts, _sass]

# Comment Service
idcomments_acct: f0a7bf6974944a38926567763cc03594

permalink: /archivers/:title/:categories/:month/:day/:year
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
